export const translations = {
  en: {
    events: "Events",
    wishList: "Wish List",
    newEventPlaceholder: "Create an event",
    addEventButton: "Add",
    alertEmptyEvent: "Enter an event title",
    inputEditEvent: "Event name",
    alertSaveEvent: "Name $title already in your events list.",
    alertEmptyWish: "Please, enter a wish title",
    wishTitleInputPlaceholder: "Title",
    wishLinkInputPlaceholder: "Link",
    saveWishButton: "Save",
    addWishButton: "Add Wish",
    renderWishesTitle: "You need to select an event.",
    alertSaveToPDF: "This event has no wishes to export.",
    saveToPDF: "Save to PDF",
  },
  ru: {
    events: "События",
    wishList: "Список желаний",
    newEventPlaceholder: "Добавьте новое событие",
    addEventButton: "Добавить",
    alertEmptyEvent: "Введите название события",
    inputEditEvent: "Название события",
    alertSaveEvent: "Событие с названием $title уже существует.",
    alertEmptyWish: "Пожалуйста, введите желание",
    wishTitleInputPlaceholder: "Название желания",
    wishLinkInputPlaceholder: "Ссылка на подарок",
    saveWishButton: "Сохранить",
    addWishButton: "Добавить желание",
    renderWishesTitle: "Пожалуйста, выберите событие.",
    alertSaveToPDF: "В этом событии пока нет желаний для экспорта.",
    saveToPDF: "Сохранить как PDF",
  },
  pl: {
    events: "Wydarzenia",
    wishList: "Lista życzeń",
    newEventPlaceholder: "Nowe wydarzenie",
    addEventButton: "Dodaj",
    alertEmptyEvent: "Wpisz nazwę wydarzenia",
    inputEditEvent: "Nazwa wydarzenia",
    alertSaveEvent: "Wydarzenie o nazwie $title już istnieje.",
    alertEmptyWish: "Proszę, wpisz życzenie",
    wishTitleInputPlaceholder: "Tytuł życzenia",
    wishLinkInputPlaceholder: "Link do prezentu",
    saveWishButton: "Zapisz",
    addWishButton: "Dodaj życzenie",
    renderWishesTitle: "Wybierz wydarzenie",
    alertSaveToPDF: "To wydarzenie nie zawiera żadnych życzeń do eksportu",
    saveToPDF: "Zapisz do PDF",
  },
};

export const locales = {
  en: "En",
  pl: "Pl",
  ru: "Ru",
};
